# Generated by Django 6.0 on 2025-12-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
