# Generated by Django 6.0 on 2025-12-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendinguser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
