# Generated by Django 6.0 on 2025-12-10 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_pendinguser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='last_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
