# Generated by Django 6.0 on 2025-12-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emailotp_last_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('forgot_password', 'Forgot Password')], default='registration', max_length=30),
        ),
    ]
