# Generated by Django 6.0 on 2025-12-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_pendinguser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='license_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='license_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
