# Generated by Django 6.0 on 2025-12-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_pendinguser_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
