# Generated by Django 6.0 on 2025-12-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_pendinguser_latitude_pendinguser_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REQUESTED_AGAIN', 'Requested Again')], default='PENDING', max_length=20),
        ),
    ]
