# Generated by Django 6.0 on 2026-01-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_workshop_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='reapply_count',
            field=models.IntegerField(default=0),
        ),
    ]
