# Generated by Django 6.0 on 2026-01-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_workshop_reapply_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='reapply_count',
        ),
    ]
