# Generated by Django 6.0 on 2026-04-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_workshop_reapply_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
