# Generated by Django 6.0 on 2026-07-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_workshop_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
