# Generated by Django 6.0 on 2026-04-07 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_chatme_receive_d79e66_idx',
        ),
        migrations.AddField(
            model_name='chatmessagerecipient',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='chat.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessagerecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
        migrations.AddIndex(
            model_name='chatmessagerecipient',
            index=models.Index(fields=['user', 'is_read'], name='chat_chatme_user_id_3d17ea_idx'),
        ),
    ]
