from django.urls import path
from .views import (
    UserRegisterView,
    MechanicRegisterView,
    WorkshopRegisterView,
    VerifyOTPView, 
    ResendOTPView, 
    LoginView,
    LogoutView, 
    GoogleAuthView, 
    ForgotPasswordVerifyOtpView, 
    ForgotPasswordResetView, 
    ForgotPasswordSendOtpView, 
    ProfileView, 
    ChangePasswordView, 
    CookieTokenRefeshView,
    WorkshopReApplyView,
    WorkshopSearchView,
    MechanicJoinRequestView,
    WorkshopMechanicRequestsView,
    WorkshopMechanicActionView,
    WorkshopMechanicRequestsView,
    WorkshopMechanicActionView,
    WorkshopMyMechanicsView,
    MechanicCurrentWorkshopView,
    MechanicLeaveWorkshopView,
    WorkshopRemoveMechanicView
)


urlpatterns = [
    path('register/user/', UserRegisterView.as_view(), name='register_user'),
    path('register/mechanic/', MechanicRegisterView.as_view(), name='register_mechanic'),
    path('register/workshop/', WorkshopRegisterView.as_view(), name='register_workshop'),
    path('verify-otp/', VerifyOTPView.as_view(),name = 'verify-otp'),
    path('resend-otp/',ResendOTPView.as_view(),name = 'resend-otp'),
    path('login/', LoginView.as_view(), name = 'token_obtain_pair'),
    path('auth/token/refresh/',CookieTokenRefeshView.as_view(), name='token_refresh'),
    path('google/', GoogleAuthView.as_view(), name='google-login'),
    path('logout/',LogoutView.as_view(), name = 'auth_logout'),
    path('forgot-password/send-otp/', ForgotPasswordSendOtpView.as_view(), name='forgot_password_send_otp'),
    path('forgot-password/verify-otp/', ForgotPasswordVerifyOtpView.as_view(), name='forgot_password_verify_otp'),
    path('forgot-password/reset/', ForgotPasswordResetView.as_view(), name='forgot_password_reset'),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("reapply-workshop/", WorkshopReApplyView.as_view(), name="reapply-workshop"),
    
    path("workshops/search/", WorkshopSearchView.as_view(), name="search-workshops"),
    path("mechanic/join/", MechanicJoinRequestView.as_view(), name="mechanic-join"),
    path("mechanic/leave/", MechanicLeaveWorkshopView.as_view(), name="mechanic-leave"),
    path("mechanic/current-workshop/", MechanicCurrentWorkshopView.as_view(), name="mechanic-current-workshop"),
    
    path("workshop/mechanic-requests/", WorkshopMechanicRequestsView.as_view(), name="workshop-mechanic-requests"),
    path("workshop/mechanic-requests/action/", WorkshopMechanicActionView.as_view(), name="workshop-mechanic-action"),
    path("workshop/mechanics/", WorkshopMyMechanicsView.as_view(), name="workshop-my-mechanics"),
    path("workshop/mechanic/remove/", WorkshopRemoveMechanicView.as_view(), name="workshop-remove-mechanic"),
]
