# Generated by Django 6.0 on 2025-12-18 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_pendinguser_latitude_pendinguser_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('issue_category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('user_latitude', models.FloatField()),
                ('user_longitude', models.FloatField()),
                ('is_platform_fee_paid', models.BooleanField(default=False)),
                ('platform_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING_FEE', 'Pending Platform Fee'), ('REQUESTED', 'Connection Requested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ESTIMATE_SHARED', 'Estimate Shared'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('estimate_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_escrow_paid', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_paid_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_requests', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='accounts.workshop')),
            ],
        ),
    ]
