# Generated by Django 6.0 on 2026-03-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
