# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='escrow_released',
            field=models.BooleanField(default=False),
        ),
    ]
