# Generated by Django 6.0 on 2025-12-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0001_initial'),
    ]

    operations = [
    ]
