# Generated by Django 6.0 on 2025-12-18 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_pendinguser_latitude_pendinguser_longitude'),
        ('service_request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='assigned_handler',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='estimate_amount',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='is_escrow_paid',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='is_platform_fee_paid',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='platform_transaction_id',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING_FEE', 'Pending Platform Fee'), ('REQUESTED', 'Connection Requested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ESTIMATE_SHARED', 'Estimate Shared'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='accounts.workshop'),
        ),
    ]
