# Generated by Django 6.0 on 2025-12-30 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_workshop_verification_status'),
        ('service_request', '0002_auto_20251218_1522'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='assigned_handler',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='estimate_amount',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='fee_paid_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='is_escrow_paid',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='is_platform_fee_paid',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='platform_transaction_id',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='workshop',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='platform_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='platform_fee_txn_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='issue_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('FEE_PAID', 'Platform Fee Paid'), ('CONNECTING', 'Connecting Workshops'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='vehicle_model',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('escrow_paid', models.BooleanField(default=False)),
                ('escrow_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_services', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='service_request.servicerequest')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='accounts.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('AUTO_REJECTED', 'Auto Rejected'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('cancelled_by', models.CharField(blank=True, choices=[('USER', 'User'), ('WORKSHOP', 'Workshop')], max_length=20, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='service_request.servicerequest')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='accounts.workshop')),
            ],
        ),
    ]
