# Generated by Django 6.0 on 2026-01-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0003_remove_servicerequest_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PLATFORM_FEE_PAID', 'Platform Fee Paid'), ('CONNECTING', 'Connecting Workshops'), ('CONNECTED', 'Connected'), ('ESTIMATE_SHARED', 'Estimate Shared'), ('SERVICE_AMOUNT_PAID', 'Service Amount Paid'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='workshopconnection',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('AUTO_REJECTED', 'Auto Rejected'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn')], max_length=20),
        ),
    ]
