# Generated by Django 6.0 on 2026-01-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_workshop_reapply_count'),
        ('service_request', '0004_alter_servicerequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceexecution',
            name='mechanics',
            field=models.ManyToManyField(blank=True, related_name='assigned_executions', to='accounts.mechanic'),
        ),
    ]
