# Generated by Django 6.0 on 2026-01-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0005_serviceexecution_mechanics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceexecution',
            name='assigned_to',
        ),
    ]
