# Generated by Django 6.0 on 2026-04-16 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_workshop_reapply_count'),
        ('service_request', '0008_alter_serviceexecution_estimate_amount_estimate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earning_type', models.CharField(choices=[('SERVICE_SHARE', 'Service Share'), ('BONUS', 'Bonus')], default='SERVICE_SHARE', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='accounts.mechanic')),
                ('service_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanic_earnings', to='service_request.serviceexecution')),
            ],
        ),
    ]
