# Generated by Django 6.0 on 2026-02-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0008_servicemessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicemessage',
            options={'ordering': ['created_at']},
        ),
    ]
