# Generated by Django 6.0 on 2026-07-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0010_mechanicreview_workshopreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceexecution',
            name='last_otp_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
