# Generated by Django 6.0 on 2026-07-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0011_serviceexecution_last_otp_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceexecution',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
